server:
    port: 0

logging:
    level:
        org.springframework: DEBUG
    
spring:
    application:
        name: hello-service
    jackson:
        serialization:
            indent-output: true

management:
    endpoints:
        web:            
            exposure:
                include: "*"

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
